/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mirzayogy.pbo2.view.kasir;

import com.mirzayogy.pbo2.view.admin.*;
import com.mirzayogy.pbo2.model.Barang;
import com.mirzayogy.pbo2.model.JenisBarang;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mirza
 */
public class PenjualanAddFrame extends javax.swing.JFrame {

    /**
     * Creates new form BarangAddFrame
     */
    public PenjualanAddFrame() {
        initComponents();
        setLocationRelativeTo(null);
//        isiDataCb();
//        tfId.setEnabled(false);
//        tfId.setText("NULL");
//        tfNamaBarang.requestFocus();
    }

    PenjualanAddFrame(Barang barang) {
        initComponents();
        setLocationRelativeTo(null);
        
        
        
//        isiDataCb();
//        tfId.setEnabled(false);
//        tfId.setText(String.valueOf(barang.getId()));
//        
//        barang.find();
//        tfNamaBarang.setText(barang.getNamaBarang());
//        tfHarga.setText(String.valueOf(barang.getHarga()));
//        
//        for (int i = 0; i < cbJenisBarang.getItemCount(); i++) {
//            JenisBarang jenisBarang = new JenisBarang();
//                cbJenisBarang.setSelectedIndex(i);
//                jenisBarang.setId(((JenisBarang) cbJenisBarang.getSelectedItem()).getId());
//                if (jenisBarang.getId() == barang.getJenisBarang().getId()) {
//                    cbJenisBarang.setSelectedIndex(i);
//                    break;
//                }
//            }
//        
//        
//        tfNamaBarang.requestFocus();
    }
    
    public void tampilkanDataBarang(ArrayList<Barang> list){
        DefaultTableModel model = (DefaultTableModel) tbBarang.getModel();
        model.setRowCount(0);
        
        if(list != null){   
            Object[] row = new Object[4];
            
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId();
                row[1] = list.get(i).getNamaBarang();
                row[2] = list.get(i).getJenisBarang().getNamajenisbarang();
                row[3] = list.get(i).getHarga();
                
                model.addRow(row);
            }
            
        }
    }
    
    
    public void isiDataCb(){
//        JenisBarang jenisBarang = new JenisBarang();
//        ArrayList<JenisBarang> list = jenisBarang.read();
//        
//        DefaultComboBoxModel model = new DefaultComboBoxModel();
//        
//        for (int i = 0; i < list.size(); i++) {
//            JenisBarang jb = list.get(i);
//            model.addElement(jb);
//        }
//        
//        cbJenisBarang.setModel(model);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfHargaBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBarang = new javax.swing.JTable();
        jtfNamaBarang = new javax.swing.JTextField();
        jtfQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jtfTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Input Data Penjualan");

        jButton6.setText("Simpan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Tutup");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Barang");

        jtfHargaBarang.setEditable(false);
        jtfHargaBarang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfHargaBarang.setText("0");
        jtfHargaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfHargaBarangKeyTyped(evt);
            }
        });

        jLabel6.setText("Cari Barang");

        tfCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCariActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga", "Qty", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tbBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Barang", "Jenis Barang", "Harga"
            }
        ));
        tbBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbBarangMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbBarang);

        jtfNamaBarang.setEditable(false);
        jtfNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNamaBarangActionPerformed(evt);
            }
        });

        jtfQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfQty.setText("0");
        jtfQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfQtyKeyTyped(evt);
            }
        });

        jLabel7.setText("Harga");

        jLabel8.setText("Qty");

        jButton2.setText("Tambahkan");

        jtfTotal.setEditable(false);
        jtfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfTotal.setText("0");
        jtfTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTotalKeyTyped(evt);
            }
        });

        jLabel9.setText("Harga x Qty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(226, 226, 226))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
//        JenisBarang jbComboBox = ((JenisBarang) cbJenisBarang.getSelectedItem());
//        
//        Barang barang = new Barang();
//        barang.setNamaBarang(tfNamaBarang.getText());
//        barang.setJenisBarang(jbComboBox);
//        barang.setHarga(Float.parseFloat(tfHarga.getText()));
//        
//        if(tfId.getText().equals("NULL")){
//            if(barang.create()){
//                dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, "Gagal Insert Data");
//            }
//        } else {
//            barang.setId(Integer.parseInt(tfId.getText()));
//            if(barang.update()){
//                dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, "Gagal Update Data");
//            }
//        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtfHargaBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfHargaBarangKeyTyped
        char enter = evt.getKeyChar();
        if (!Character.isDigit(enter) && enter != KeyEvent.VK_PERIOD) {
            evt.consume();
//            System.out.println(enter);
        }
    }//GEN-LAST:event_jtfHargaBarangKeyTyped

    private void tfCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Barang barang = new Barang();
        ArrayList<Barang> list = barang.search(tfCari.getText());
//        tampilkanData(list);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNamaBarangActionPerformed

    private void jtfQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQtyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfQtyKeyTyped

    private void jtfTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Barang barang = new Barang();
        ArrayList<Barang> list = barang.read();
        tampilkanDataBarang(list);
    }//GEN-LAST:event_formWindowActivated

    private void tbBarangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBarangMouseReleased
         TableModel model = tbBarang.getModel();
        int barisTerpilih = tbBarang.getSelectedRow();

        if(barisTerpilih >= 0){
           
            String idBarang = model.getValueAt(barisTerpilih,0).toString();
            String namaBarang = model.getValueAt(barisTerpilih,1).toString();
            String hargaBarang = model.getValueAt(barisTerpilih,3).toString();
            
            jtfNamaBarang.setText(namaBarang);
            jtfHargaBarang.setText(hargaBarang);


        } 
    }//GEN-LAST:event_tbBarangMouseReleased

    private void jtfQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfQtyKeyReleased
        double harga = Float.parseFloat(jtfHargaBarang.getText());
        double qty = Float.parseFloat(jtfQty.getText());
        
        double total = harga * qty;
        
        jtfTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jtfQtyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfHargaBarang;
    private javax.swing.JTextField jtfNamaBarang;
    private javax.swing.JTextField jtfQty;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTable tbBarang;
    private javax.swing.JTextField tfCari;
    // End of variables declaration//GEN-END:variables
}
